name: Deploy Development Environment

on:
   pull_request:
      branches:
         - dev

jobs:
   deployment:
      runs-on: ubuntu-latest
      environment: development
      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Install dependencies
           run: npm install

         - name: Build Next.js app
           run: npm run build
