name: Deploy Production Environment

on:
   push:
      branches:
         - main

jobs:
   deployment:
      runs-on: ubuntu-latest
      environment: production
      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Install dependencies
           run: npm ci

         - name: Build Next.js app
           run: npm run build
