name: Verify Build

on:
   pull_request:
      branches:
         - production
         - staging
         - dev

jobs:
   deployment:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Install dependencies
           run: npm i

         - name: Lint code
           run: npm run lint

         - name: Build Next.js app
           run: npm run build
